#: import RiseInTransition kivy.uix.screenmanager.RiseInTransition
#: import SlideTransition kivy.uix.screenmanager.SlideTransition



<ElementCard@MDCard>:
    radius: "10dp"
    spacing: "10dp"
    padding: "10dp"
    image: " "
    text: " " 
    sub_text: " "
    orientation: "vertical"
    ripple_behavior: True
    on_release: 
        app.root.transition = RiseInTransition()
    image: 
        root.image
    MDBoxLayout:
        orientation: "vertical"
        MDLabel: 
            text: root.text
            halign: "center"
        MDLabel: 
            text: root.sub_text
            halign: "center"

<CustomizeScreen@MDBoxLayout>
    orientation: "vertical"
    text: ""
    padding: 100
    MDLabel:
        text: root.text
        halign: "center"
        pos_hint: {"center_x": 0.5}
    MDFillRoundFlatButton: 
        text: "Regresar"
        pos_hint: {"center_x": 0.5}
        on_release: 
            app.root.current = "screen_principal"
            app.root.transition = SlideTransition(direction= "left")


<ui>:
    MDScreen:
        name: "screen_principal"
        md_bg_color: (245,245,245)
        MDBoxLayout:
            orientation: "vertical"
            MDBoxLayout:
                size_hint:  1, 0.6
                orientation: "vertical"
                padding: "10dp"
                MDCard: 
                    radius: "10dp"
                    padding: "10dp"

                    MDLabel:
                        markup: True
                        text: "[size=36][b]Messitación[/b][/size]"
                        halign: "center"  # Adjust the indentation here
                        pos_hint: {'center_x': 0.5,'center_y': 0.5}
                        font_color: (39, 40, 41)


            MDGridLayout:
                cols: 2
                size_hint: 1, .8
                padding: ['10dp', '10dp', '10dp', '10dp']
                
                ElementCard:
                    text: 'Messitación 1:'
                    sub_text: 'Elementos'
                    font_color: (39, 40, 41)
                    on_release:
                        root.current = "screen1"
                
                ElementCard:
                    text: 'Messitación 1:'
                    sub_text: 'Elementos'
                    font_color: (39, 40, 41)
                    on_release:
                        root.current = "screen2"
                
                ElementCard:
                    text: 'Messitación 1:'
                    sub_text: 'Elementos'
                    font_color: (39, 40, 41)
                    on_release:
                        root.current = "screen3"

    MDScreen:        
        name: "screen1"
        CustomizeScreen:
            text: "Pantalla uno"

    MDScreen:        
        name: "screen2"
        CustomizeScreen:
            text: "Pantalla uno"
    
    MDScreen:        
        name: "screen3"
        CustomizeScreen:
            text: "Pantalla uno"